# Python Practical Exam

© Explore Data Science Academy
## Instructions to students
* **DO NOT ADD / REMOVE CELLS FROM THIS NOTEBOOK, AND DO NOT CHANGE THE NAMES OF THE FUNCTIONS REQUIRED FOR TESTING.**
  
* This exam consits of six questions. Each of the questions are independent and do not require you to use functions built from previous questions. You can answer any question in any order you like.

* Ensure that the answers to your questions do not contain `syntax` or `indentation` errors. Questions with these errors will break the autograder, and will mark the _**entire exam**_ as incorrect. The autograder will give you an error message if this is the case. Use this error message to correct the offending code, or, comment it out before resubmitting.
* You will be able to make _**multiple submissions**_ to the autograder. Use this ability to check whether a question you have answered is correct before proceeding to the next question.
* Only place code in sections that contain the `# Your code here` comment.
* We have provided some expected outputs for your code. Use these to determine whether your code is behaving as intended.
* Some questions may have multiple requirements. It is possible to receive partial marks in these questions, so if you get stuck, try submitting to the autograder before moving on.

In [2]:
import numpy as np
import pandas as pd

## Section 1: Numerical Computation
### Question 1
We have a rope and want to cut the rope into 4 pieces to make a square. Given a rope of length $x$, what is the largest square (by area) that can be built given that a side, $s$, of the square can only be integer values? Units of measurement can be ignored, we are only interested in the numerical value of the solution.
<p align="center">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/python_fundamentals/python_exam/Largest_Square_Rope.jpg"
     alt="Largest Square"
     style="float: center; padding-bottom=0.5em"
     width=700px/>
     <br>
     <em>Figure 1: Area of the largest square enclosed by a rope </em>
</p>    

**Function specifications**

*Argument(s):*

- **x** `(float)` $\rightarrow$ the length of the rope

*Return:* 

- **area** `(int)` $\rightarrow$ the area of the square formed by the rope

> 💡**HINT**💡
>
>The perimeter of the square cannot exceed the length of the rope.

<br>

>**SOLUTION**
>
>A square will always have 4 equal sides, so the perimeter of the square can be given by:
>
>$p=4s$
>
>However the perimeter of the square cannot exceed the length of the rope, so we know for a fact that:
>
>_**Contraint:**_ $p \leq x$
>
>$\implies 4s \leq x$
>
>$\implies s \leq \frac{x}{4} $  where $\frac{x}{4} \in \R$
>
>A further constraint is that the length of a single side has to be an integer value, to do this we can discard the fractional part of the real number - leaving an integer value. This can be achieved by using the `np.floor()` function:
>
>$\implies s = \lfloor \frac{x}{4} \rfloor$  where $\lfloor \frac{x}{4} \rfloor \in \Z$
>
>Now to obtain the area of the square: 
>
>$Area =s^2$
>
>$Area =\lfloor \frac{x}{4} \rfloor^2 $
>
>The above computation can be used to write the required python function

In [140]:
### START FUNCTION
def largest_square(x):
    s = int(np.float(x/4))
    area = s**2
    return area
### END FUNCTION

In [141]:
largest_square(279)

4761

_**Expected Outputs:**_
```python
largest_square(12) == 9
largest_square(41.5) == 100
largest_square(324) == 6561
```

### Question 2
Given a square matrix of size $n\times n $ that only contains integers, compute the sum of the two diagonals. If the dimension of the square matrix is odd, make sure that you do not double count the value at the center of the matrix.

<p align="center">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/python_fundamentals/python_exam/Sum_of_diagonals.jpg"
     alt="Sum of diagonals"
     style="float: center; padding-bottom=0.5em"
     width=50%/>
     <br>
     <em>Figure 2: Sum of diagonals</em>
</p>    


**Function Specifications**

*Arguments:*
- **matrix** `(numpy.ndarray)` $\rightarrow$ input matrix to be used for computing the sum

*Return:*
- **sum** `(int)` $\rightarrow$  return the sum of the two diagonals


In [142]:
### START FUNCTION
def sum_of_diagonals(matrix):
    diag_1=0
    diag_2=0
    k = matrix.shape[1]-1
    for i in range(matrix.shape[0]):
        diag_1 += matrix[i][i]
        diag_2 += matrix[i][k]
        k -=1
    if matrix.shape[0]%2 != 0:
        mid = int(np.floor(matrix.shape[0]/2))
        sum = diag_1+diag_2-matrix[mid][mid]  
    else:
        sum = diag_1+diag_2 
    return sum
### END FUNCTION

In [143]:
matrix =np.random.randint(10,size=(7,7))
print(matrix)
sum_of_diagonals(matrix)


[[2 8 7 6 3 8 6]
 [9 8 3 8 2 5 3]
 [5 1 4 8 2 9 0]
 [9 5 2 8 4 0 2]
 [8 9 1 2 2 2 6]
 [7 4 2 3 5 3 8]
 [5 0 0 5 9 1 8]]


58

_**Expected outputs:**_
```python
matrix = np.array([[7, 0, 8],
                   [6, 9, 1],
                   [3, 8, 4]])
sum_of_diagonals(matrix)==31


matrix = np.array([[4, 1, 1, 1],
                   [1, 3, 8, 0],
                   [0, 8, 5, 7],
                   [1, 6, 1, 3]])
sum_of_diagonals(matrix)==33
```

## Section 2: Strings and Lists

### Question 3

Write a function that computes the ratio of vowels vs consonants ($\frac{vowels}{consonants}$) in a given sentence, the ratio should be given as a floating-point number rounded off to two decimal places. When writing your function be sure to appropriately cater for the following punctuation marks:
- apostrophes (');
- quotations (");
- full-stops (.);
- commas (,);
- exclamations (!);  
- question marks (?);
- colons (:);and
- semicolons (;)

*Arguments:*
- **sentence** `(string)` $\rightarrow$ sentence required to compute the ratio

*Return:*
- **ratio** `(float)` $\rightarrow$ a ratio that describes the number of vowels to consonants: vowels/consonants

> 💡**HINT**💡
>
>Remember to cater for the white spaces that appear in your sentence.

In [147]:
### START FUNCTION
def vowel_consonant_ratio(sentence):
    vowel_count=0
    consonant_count=0
    for character in sentence:
        if character not in '\'".,!?;:aeiouAEIOU ':
            consonant_count += 1
        elif character in 'aeiouAEIOU':
            vowel_count +=1
    return round(vowel_count/consonant_count,2)
### END FUNCTION

In [148]:
vowel_consonant_ratio("Thomas! Where have you been?")

0.83

***Expected outputs***

```python
vowel_consonant_ratio("This is a random sentence!")==0.62
vowel_consonant_ratio("Thomas! Where have you been?")==0.83
```

### Question 4

Write a function that will redact every third word in a sentence. Make use of the hashtag (`#`) symbol, to redact the characters that make up the word. i.e. if the word is 5 characters long, then a string of 5 hashtags should replace that word. However, this should not redact any of the following punctuation marks:
- apostrophes (');
- quotations (");
- full-stops (.);
- commas (,);
- exclamations (!);  
- question marks (?);
- colons (:); and
- semicolons (;)

*Arguments:*
- **sentence** `(string)` $\rightarrow$ sentence that needs to be redacted

*Return:*
- **redacted sentence** `(string)`$\rightarrow$ every third word should be redacted

In [149]:
### START FUNCTION
def redact_words(sentence):
    words = sentence.split(" ")
    redacted_sentence=""
    i=1
    for word in words:
        if i%3==0:
            redaction=""
            for character in word:
                if character in '\'".,!?;:':
                    redaction = redaction + character
                else:
                    redaction = redaction +'#'
            redacted_sentence = redacted_sentence+" "+redaction
        else:
            redacted_sentence = redacted_sentence+" "+word
        i+=1
    return redacted_sentence.strip()
### END FUNCTION   

In [150]:
sentence = "Explorer, this is why you shouldn't come to a test unprepared."
redact_words(sentence)

"Explorer, this ## why you #######'# come to # test unprepared."

***Expected outputs***

```python
sentence = "My dear Explorer, do you understand the nature of the given question?"
redact_words(sentence) ==  'My dear ########, do you ########## the nature ## the given ########?'

sentence = "Explorer, this is why you shouldn't come to a test unprepared."
redact_words(sentence)=="Explorer, this ## why you #######'# come to # test unprepared."

```

### Question 5

Given an alphanumeric list, separate it into three different lists stored in a dictionary:

- the first list should only contain lowercase letters;
- the second list should only contain uppercase letters; and
- the third list should only contain numbers

Each list stored in the dictionary should be stored in ascending order. Use the following naming convention when creating your lists:
- numbers
- uppercase
- lowercase

Please make sure that you adhere to the above instruction, as the name of your lists will be used to mark your function.

*Arguments:*
- **character_list:** `(list)` $\rightarrow$ sentence that needs to be redacted

*Return:*
- **dictionary** `(dict)` $\rightarrow$  dictionary containing all three lists

In [151]:
### START FUNCTION
def create_dictionary(character_list):
    dictionary={'numbers':[],'uppercase':[],'lowercase':[]}
    for character in character_list:
        try:
            int(character)
            dictionary['numbers'].append(character)
        except:
            if character.isupper():
                dictionary['uppercase'].append(character)
            elif character.islower():
                dictionary['lowercase'].append(character)
    for item in dictionary:
        dictionary[item].sort()
    return dictionary
### END FUNCTION


In [152]:
lst = [2,'j','K','o',6,'x',5,'A',3.2]
create_dictionary(lst)

{'numbers': [2, 3.2, 5, 6],
 'uppercase': ['A', 'K'],
 'lowercase': ['j', 'o', 'x']}

***Expected outputs***

```python
lst = [2,'j','K','o',6,'x',5,'A',3.2]
create_dictionary(lst)

{'numbers': [2, 3.2, 5, 6],
 'uppercase': ['A', 'K'],
 'lowercase': ['j', 'o', 'x']}
 ```



## Section 3: Dataframes
You will need the below dataframes in order to answer the following questions.

_**DO NOT ALTER THESE DATAFRAMES AS DOING SO CAN LEAD TO A NEGATIVE MARK**_



In [157]:
country_map_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/country_code_map.csv', index_col='Country Code')
population_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/world_population.csv', index_col='Country Code')
meta_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/AnalyseProject/metadata.csv', index_col='Country Code')

_**Dataframe specifications:**_

The dataframes provide information about the population of the world for various years. Some things to note:
* All dataframes have a `Country Code` as an index, which is a three-letter code referring to a country.
* The `country_map_df` data maps the `Country Code` to a `Country Name`.
* The `population_df` data contains information on the population for a given country between the years 1960 and 2017.
* The `meta_df` data contains meta-information about each country, including its geographical region, its income group, and a comment on the country as a whole.

### Question 6

Write a function that will return a list of countries for a specified region and income group. If the specified region and income group does not return a country, return `None` as the value.


**Function specifications**

*Argument(s):*
- **region** `(string)` $\rightarrow$ the region you want to query
- **income_group** `(string)` $\rightarrow$ the income group you want to query


*Return:*
- **countries** `(list)` $\rightarrow$ return a list of countries that match the search criteria or **`None`** if no countries are found

In [158]:
### START FUNCTION
def find_countries_by_region_and_income(region,income_group):
    df = country_map_df.join(meta_df, on='Country Code')
    df = df[(df['Region']==str(region))& (df['Income Group']==str(income_group))]
    if df.shape[0]== 0 :
        return None
    else:
        return list(df['Country Name'].values)
### END FUNCTION


In [201]:
countries = find_countries_by_region_and_income('Sub-Saharan Africa','Upper middle income')
countries

['Botswana',
 'Gabon',
 'Equatorial Guinea',
 'Mauritius',
 'Namibia',
 'South Africa']

***Expected Output***

```python
find_countries_by_region_and_income('South Asia','High income')==None
find_countries_by_region_and_income('Europe & Central Asia','Low income')==['Tajikistan']
find_countries_by_region_and_income('Sub-Saharan Africa','Upper middle income')==['Botswana','Gabon','Equatorial Guinea','Mauritius','Namibia','South Africa']
```